fastdfs:
  bufferSize: 1024
  configpath: classpath:config/fastdfs-client.properties

#数据库连接相关
spring:
  datasource:
    file-manage:
      url: jdbc:mysql://49.234.215.112:3306/file_manage?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
      password: shiyonglong2
      username: skty
  mvc:
    static-path-pattern: /static/**

server:
  port: 8080
  servlet:
    context-path: /fileManage


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      skty:
        plugins:
          filemanage:
            db:
              mapper: debug




