fastdfs:
  bufferSize: 1024
  configpath: classpath:config/fastdfs-client.properties

#数据库连接相关
spring:
  datasource:
    file-manage:
      url: jdbc:mysql://49.234.215.112:3306/file_manage?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
      password: shiyonglong2
      username: skty
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:templates/
      suffix: .html
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: dd/MM/yyyy
  thymeleaf:
    prefix: classpath:templates/
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  redis:
    host: 49.234.215.112
    port: 6379
    password: shiyonglong2

server:
  port: 8080
  servlet:
    context-path: /fileManage


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      skty:
        plugins:
          filemanage:
            db:
              mapper: debug

